### PR TITLE
changed hbnb.datro.xyz to React.js

### PR DESCRIPTION
**Pull request by sdo977**

### CODE REVIEW

**Comment by rainbowunicorn18** [comment]
I have done.
Can we talk in here? or could you let me know your skype info?

**Comment by unclehowell** [comment]
> I have done. Can we talk in here? or could you let me know your skype info?

The netlify deploy preview is showing a blank white page for /static/hbnb so I'm still reluctant to approve this request because if I did the url https://hbnb.datro.xyz would go from working to a blank white page.

**Comment by unclehowell** [comment]
> I have done. Can we talk in here? or could you let me know your skype info?

This is what I see in the deploy preview above , just a white blank page https://deploy-preview-6--practical-franklin-8261ab.netlify.app/build

**Comment by rainbowunicorn18** [comment]
To deploy our React project to the hbnb.datro.xyz domain, we will need to follow these general steps:
-Build React project: I have done.
-Access your server or hosting provider: We need to have access to the server where hbnb.datro.xyz domain is hosted.
This might be a web hosting service, a cloud server (like AWS EC2), or your own server.
-Upload build files: Once React project is built, you will have a set of static files(HTML, CSS, JavaScript, etc) located in the build directlry of project. Upload these files to your server using FTP, SSH, or whatever method your hosting provider supports. You will typically upload them to a directlry like /public_html or /var/www.
-Configure your server: Ensure that your server is set up to serve your React application correctly. This might involve configuring your web server (such as Apache or Nginx) to serve the index.html file as the default document and to handle routing correctly (if you're using React Router).
-Update DNS settings: If hbnb.datro.xyz is a custom domain, you'll need to update the DNS settings to point to the IP address of your server. This is usually done through your domain registrar's control panel.
-Test your deployment: Once everything is set up, visit hbnb.datro.xyz in your web browser to make sure your React application is being served correctly.
-Continuous Deployment (Optional): If you plan to frequently update your React application, consider setting up a continuous deployment pipeline using tools like GitHub Actions, GitLab CI/CD, or Jenkins. This will automate the process of building and deploying your React project whenever you push changes to your repository.
-By following these steps, you should be able to deploy your React project to the hbnb.datro.xyz domain and have it accessible to your users.

**Comment by unclehowell** [comment]
> To deploy our React project to the hbnb.datro.xyz domain, we will need to follow these general steps: -Build React project: I have done. -Access your server or hosting provider: We need to have access to the server where hbnb.datro.xyz domain is hosted. This might be a web hosting service, a cloud server (like AWS EC2), or your own server. -Upload build files: Once React project is built, you will have a set of static files(HTML, CSS, JavaScript, etc) located in the build directlry of project. Upload these files to your server using FTP, SSH, or whatever method your hosting provider supports. You will typically upload them to a directlry like /public_html or /var/www. -Configure your server: Ensure that your server is set up to serve your React application correctly. This might involve configuring your web server (such as Apache or Nginx) to serve the index.html file as the default document and to handle routing correctly (if you're using React Router). -Update DNS settings: If hbnb.datro.xyz is a custom domain, you'll need to update the DNS settings to point to the IP address of your server. This is usually done through your domain registrar's control panel. -Test your deployment: Once everything is set up, visit hbnb.datro.xyz in your web browser to make sure your React application is being served correctly. -Continuous Deployment (Optional): If you plan to frequently update your React application, consider setting up a continuous deployment pipeline using tools like GitHub Actions, GitLab CI/CD, or Jenkins. This will automate the process of building and deploying your React project whenever you push changes to your repository. -By following these steps, you should be able to deploy your React project to the hbnb.datro.xyz domain and have it accessible to your users.

**Pull request merged**
